DROP DATABASE IF EXISTS;
CREATE DATABASE commerceDB;
USE commerceDB;

CREATE TABLE items(
  id PRIMARY KEY AUTO_INCREMENT INT NOT NULL,
  itemID INT NOT NULL,
  itemName VARCHAR(40) NOT NULL,
  category VARCHAR(40) NOT NULL
  price VARCHAR(40) NOT NULL
)

CREATE TABLE itemstyles(
  id PRIMARY KEY AUTO_INCREMENT INT NOT NULL,
  style_id INT NOT NULL,
  item_id INT NOT NULL
)


CREATE TABLE styles(
  id PRIMARY KEY AUTO_INCREMENT INT NOT NULL,
  style_id INT NOT NULL,
  itemName VARCHAR(40) NOT NULL,
  price VARCHAR(40) NOT NULL,
  photos
)